;>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
;				SW Farmer								   												  ;
;				By mblom122								   												  ;
;>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

;###############################################
;				AutoGenerated
;###############################################
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

; ###############################################
; 					Include
; ###############################################

#Include lib\variables.ahk
#Include lib\functions.ahk
#Include lib\gui.ahk


; ###############################################
				; Initialize MouseCoords
; ###############################################
; Opt("MouseCoordMode", 2) ;1=absolute, 0=relative, 2=client
; Opt("SendKeyDownDelay", 80)

; ###############################################
				; Hot keys
; ###############################################
; HotKeySet('{F5}', 'Quit')
; HotKeySet('{F4}', 'TogglePause')
; HotKeySet('{F3}', 'ToggleRefill')
; HotKeySet('{F1}', "checkForImage")

; ###############################################
				; Main loop
; ###############################################

runtime = A_TickCount

Loop
{
	
	UpdateUi()
	CalcTimes()
	
	sleep, 100
}

	; If $Paused = False Then
		; If WinActive("Nox App Player") Then
			; $status = ""
			; CheckLocation()

		; Else
			; $status = "Nox App is not active"
		; EndIf
	; Else
		; $status = "Paused"
	; EndIf
; ~ 	CheckMenu()
; ~ 	offsetlist()
; ~ 	StatsDisplay()
	; #cs
	; $windows = WinList("Diablo III")

	; For $i = 1 to $windows[0][0]
	   ; Sleep(2000)
	   ; WinActivate($windows[$i][1])
	; Next
	; #ce
	; UpdateUi()
	; Sleep(100)
; WEnd

; ###############################################
				; Gui Functions
; ###############################################

Quit:
	ExitApp

SelectMap:
Gui, Submit, nohide
	If (ddlSelectedMap = "Chiruka" or ddlSelectedMap = "Faimon" or ddlSelectedMap = "Vrofagus" or ddlSelectedMap = "Hydeni" or ddlSelectedMap = "Tamor")
		GuiControl,, ddlSelectedDiff, |Normal||Hard|Hell
	Else If (ddlSelectedMap = "Dragons" or ddlSelectedMap = "Giants" or ddlSelectedMap = "Necro")
		GuiControl,, ddlSelectedDiff, |B1|B2|B3|B4|B5|B6|B7|B8|B9|B10||
	Else If (ddlSelectedMap = "HoMagic" or ddlSelectedMap = "HoDark" or ddlSelectedMap = "HoFire" or ddlSelectedMap = "HoLight" or ddlSelectedMap = "HoWater" or ddlSelectedMap = "HoWind")
		GuiControl,, ddlSelectedDiff, |B1|B2|B3|B4|B5|B6|B7||B8|B9|B10|
	Else If (ddlSelectedMap = "HoHeroes")
		GuiControl,, ddlSelectedDiff, |B1||B2|B3||
	Else If (ddlSelectedMap = "ToA")
		GuiControl,, ddlSelectedDiff, |Normal||Hard|
	Else
		GuiControl,, ddlSelectedDiff, |none||
return

SelectDiff:
Gui, Submit, nohide

return
GuiMove:
   PostMessage, 0xA1, 2
return
ToggleRefill:
return
TogglePause:
return